"""Read-mostly projector monitoring with an explicit, locked control plane.

PJLink is used as the common transport. Vendor profiles describe optional
capabilities; they never imply that a command is safe or supported on every
model. Control is disabled until explicitly enabled by the integration.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any
import hashlib
import socket

VENDOR_PROFILES = {
    "panasonic": {"name": "Panasonic", "preferred": ["webapi", "lan", "pjlink"]},
    "digital_projection": {"name": "Digital Projection", "preferred": ["lan", "pjlink"]},
    "christie": {"name": "Christie", "preferred": ["snmp", "lan", "pjlink"]},
    "barco": {"name": "Barco", "preferred": ["lan", "pjlink"]},
    "epson": {"name": "Epson", "preferred": ["snmp", "pjlink"]},
    "sony": {"name": "Sony", "preferred": ["lan", "pjlink"]},
    "nec_sharp": {"name": "NEC / Sharp", "preferred": ["pjlink"]},
}


@dataclass
class ProjectorState:
    host: str
    port: int = 4352
    manufacturer: str | None = None
    model: str | None = None
    power: str | None = None
    input_source: str | None = None
    av_mute: str | None = None
    errors: list[str] = field(default_factory=list)
    temperatures_c: dict[str, float] = field(default_factory=dict)
    source_hours: dict[str, float] = field(default_factory=dict)
    online: bool = False
    last_error: str | None = None


class ProjectorController:
    """Build PJLink commands and enforce the integration's output lock."""

    def __init__(self, *, control_enabled: bool = False) -> None:
        self.control_enabled = control_enabled

    def set_control_enabled(self, enabled: bool) -> None:
        self.control_enabled = bool(enabled)

    def command(self, name: str, value: str | None = None) -> str:
        if not self.control_enabled:
            raise PermissionError("projector control is disabled")
        commands = {
            "power_on": "%1POWR 1",
            "standby": "%1POWR 0",
            "av_mute_on": "%1AVMT 31",
            "av_mute_off": "%1AVMT 30",
        }
        if name == "input":
            if not value:
                raise ValueError("input value required")
            return f"%1INPT {value}"
        if name not in commands:
            raise ValueError(f"unsupported projector command: {name}")
        return commands[name]

    def send_pjlink(self, host: str, port: int, name: str, value: str | None = None, timeout: float = 3.0) -> str:
        """Send one explicitly authorized, unauthenticated PJLink command.

        The transport is deliberately conservative: authentication challenges are
        rejected rather than guessed, and only commands generated by ``command``
        are sent.
        """
        command = self.command(name, value)
        with socket.create_connection((host, port), timeout=timeout) as sock:
            sock.settimeout(timeout)
            banner = sock.recv(256)
            if not banner.startswith(b"PJLINK "):
                raise ConnectionError("not a PJLink endpoint")
            if b"PJLINK 1" in banner or b"PJLINK 2" in banner:
                # Authenticated PJLink requires a password challenge. Do not
                # attempt authentication without an explicit credential flow.
                if b"0" not in banner.split()[-1:]:
                    raise PermissionError("PJLink authentication is required")
            sock.sendall((command + "\r").encode("ascii"))
            response = sock.recv(1024).decode("ascii", errors="replace").strip()
            if response.startswith("%1ERR"):
                raise RuntimeError(response)
            return response

    def snapshot(self, state: ProjectorState) -> dict[str, Any]:
        return {
            "host": state.host,
            "port": state.port,
            "manufacturer": state.manufacturer,
            "model": state.model,
            "power": state.power,
            "input_source": state.input_source,
            "av_mute": state.av_mute,
            "errors": list(state.errors),
            "temperatures_c": dict(state.temperatures_c),
            "source_hours": dict(state.source_hours),
            "online": state.online,
            "last_error": state.last_error,
            "control_enabled": self.control_enabled,
        }
