"""Philips-Hue-like DMX -> HA lighting zones.

Zones are receive-only DMX consumers. They never emit DMX/sACN/Art-Net. RDM is
represented as a passive listening/identification policy; no RDM discovery or
write command is generated by this module.
"""
from __future__ import annotations

from dataclasses import dataclass, asdict
from time import monotonic
from typing import Any
import math

from .hue_catalog import get as hue_model
from .fixture_profiles import get as fixture_profile


@dataclass
class DmxHAZone:
    zone_id: str
    name: str
    universe: int
    entity_ids: tuple[str, ...] = ()
    mode: str = "dimmer"
    channels: tuple[int, ...] = (1,)
    source: str | None = None
    enabled: bool = True
    rdm_enabled: bool = False
    fixture_type: str = ""
    fixture_profile: str = ""
    fixture_types: dict[str, str] | None = None
    hue_model_id: str = ""
    min_interval_ms: int = 100
    deadband: float = 0.0
    invert: bool = False
    dimmer_curve: str = "linear"

    def __post_init__(self):
        if self.fixture_types is None:
            self.fixture_types = {}
        if not 1 <= int(self.universe) <= 63999:
            raise ValueError("Universe must be 1..63999")
        if not self.channels or any(int(c) < 1 or int(c) > 512 for c in self.channels):
            raise ValueError("DMX channels must be 1..512")
        needed = {"dimmer": 1, "switch": 1, "cct": 1, "rgb": 3, "rgbw": 4}.get(self.mode, 1)
        if len(self.channels) < needed:
            raise ValueError(f"Zone mode {self.mode} needs {needed} channels")

    def snapshot(self):
        d = asdict(self)
        d["channels"] = list(self.channels)
        d["entity_ids"] = list(self.entity_ids)
        d["hue_capabilities"] = hue_model(self.hue_model_id) if self.hue_model_id else None
        d["fixture_profile"] = fixture_profile(self.fixture_profile).snapshot() if self.fixture_profile else None
        return d


class DmxHAZoneEngine:
    def __init__(self):
        self.zones: dict[str, DmxHAZone] = {}
        self._last_sent: dict[str, tuple[float, tuple[Any, ...]]] = {}
        self.rdm_observations: dict[str, dict[str, Any]] = {}

    def add(self, zone: DmxHAZone):
        self.zones[zone.zone_id] = zone

    def remove(self, zone_id: str):
        self.zones.pop(zone_id, None)
        self._last_sent.pop(zone_id, None)
        self.rdm_observations.pop(zone_id, None)

    @staticmethod
    def _pct(v: int, invert: bool, curve: str = "linear") -> int:
        x = max(0, min(255, int(v))) / 255.0
        if invert:
            x = 1.0 - x
        curve = (curve or "linear").lower()
        if curve == "gamma_1_8": y = x ** 1.8
        elif curve == "gamma_2_0": y = x ** 2.0
        elif curve == "gamma_2_2": y = x ** 2.2
        elif curve == "gamma_2_4": y = x ** 2.4
        elif curve in {"logarithmic", "dali_log"}: y = (math.exp(4.0 * x) - 1.0) / (math.exp(4.0) - 1.0)
        elif curve == "s_curve": y = x * x * (3.0 - 2.0 * x)
        else: y = x
        return round(max(0.0, min(1.0, y)) * 100)

    def process(self, universe: int, source: str | None, values: bytes | list[int], now=None):
        now = monotonic() if now is None else now
        vals = [int(v) for v in values[:512]]
        proposals = []
        for z in self.zones.values():
            if not z.enabled or int(z.universe) != int(universe):
                continue
            if z.source and z.source != source:
                continue
            selected = [vals[c - 1] if c <= len(vals) else 0 for c in z.channels]
            if z.invert:
                selected = [255 - v for v in selected]
            service = "turn_on"
            mode = z.mode
            if mode == "dimmer":
                payload = {"brightness_pct": self._pct(selected[0], False, z.dimmer_curve)}
                keyvals = tuple(payload.values())
            elif mode == "switch":
                on = selected[0] > 0
                service = "turn_on" if on else "turn_off"
                payload = {}
                keyvals = (service,)
            elif mode == "rgb":
                payload = {"rgb_color": selected[:3]}
                keyvals = tuple(selected[:3])
            elif mode == "rgbw":
                payload = {"rgbw_color": selected[:4]}
                keyvals = tuple(selected[:4])
            elif mode == "cct":
                payload = {"color_temp_kelvin": round(1500 + self._pct(selected[0], False) * 45)}
                keyvals = tuple(payload.values())
            else:
                payload = {}
                keyvals = tuple(selected)
            last = self._last_sent.get(z.zone_id)
            if last:
                last_t, last_vals = last
                if z.min_interval_ms and (now - last_t) * 1000 < z.min_interval_ms:
                    continue
                if z.deadband and last_vals and len(last_vals) == len(keyvals) and max(abs(float(a) - float(b)) for a, b in zip(keyvals, last_vals)) < z.deadband:
                    continue
            self._last_sent[z.zone_id] = (now, tuple(keyvals))
            # One HA service call per zone instead of one call per lamp. This
            # dramatically reduces event-bus pressure when a zone contains many
            # Hue/HA lights and lets the downstream integration apply its own
            # batching/rate policy.
            if z.entity_ids:
                proposals.append({
                    "zone_id": z.zone_id,
                    "domain": "light",
                    "service": service,
                    "entity_id": list(z.entity_ids),
                    "data": dict(payload),
                    "mode": mode,
                    "entity_count": len(z.entity_ids),
                    "hue_model_id": z.hue_model_id or None,
                })
        return proposals

    def observe_rdm(self, zone_id: str, uid: str, manufacturer: str | None = None, model: str | None = None, fixture_type: str | None = None):
        """Record an RDM observation supplied by an external passive receiver."""
        zone = self.zones.get(zone_id)
        if not zone or not zone.rdm_enabled:
            return False
        self.rdm_observations[zone_id] = {
            "uid": str(uid),
            "manufacturer": manufacturer,
            "model": model,
            "fixture_type": fixture_type or zone.fixture_type or zone.fixture_profile or None,
            "fixture_type_by_lamp": dict(zone.fixture_types or {}),
        }
        return True

    def snapshot(self):
        return [z.snapshot() for z in self.zones.values()]

    def rdm_snapshot(self):
        return dict(self.rdm_observations)
